/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Nicholas.Sixbury
 */
public class ThresholdDialog extends javax.swing.JDialog {
    
    public int thresholdToReturn = 160;

    /**
     * Creates new form ThresholdDialog
     */
    public ThresholdDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }//end constructor

    /**
     * Updates the interface based on thresholdToReturn value.
     */
    public void updateInterface() {
        if (thresholdToReturn == 160) {
            uxTh160Btn.setSelected(true);
            uxTh180Btn.setSelected(false);
            uxThOtherBtn.setSelected(false);
            uxOtherThSpnr.setValue(thresholdToReturn);
        }
        else if (thresholdToReturn == 180) {
            uxTh160Btn.setSelected(false);
            uxTh180Btn.setSelected(true);
            uxThOtherBtn.setSelected(false);
            uxOtherThSpnr.setValue(thresholdToReturn);
        }
        else {
            uxTh160Btn.setSelected(false);
            uxTh180Btn.setSelected(false);
            uxThOtherBtn.setSelected(true);
            uxOtherThSpnr.setValue(thresholdToReturn);
        }
    }//end updateInterface()

    @Override
    public void setVisible(boolean visibility) {
        updateInterface();
        super.setVisible(visibility);
    }//end setVisible

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uxSetThBtnGrp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        uxTh160Btn = new javax.swing.JRadioButton();
        uxThOtherBtn = new javax.swing.JRadioButton();
        uxTh180Btn = new javax.swing.JRadioButton();
        uxOtherThSpnr = new javax.swing.JSpinner();
        uxConfirmBtn = new javax.swing.JButton();
        uxCancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Set Threshold For Image Processing (default: 160)");

        uxSetThBtnGrp.add(uxTh160Btn);
        uxTh160Btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uxTh160Btn.setSelected(true);
        uxTh160Btn.setText("TH 160");

        uxSetThBtnGrp.add(uxThOtherBtn);
        uxThOtherBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uxThOtherBtn.setText("TH Other");

        uxSetThBtnGrp.add(uxTh180Btn);
        uxTh180Btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uxTh180Btn.setText("TH 180");

        uxOtherThSpnr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uxOtherThSpnr.setModel(new javax.swing.SpinnerNumberModel(160, 0, 255, 1));

        uxConfirmBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uxConfirmBtn.setText("Confirm");
        uxConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxConfirmBtnActionPerformed(evt);
            }
        });

        uxCancelBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uxCancelBtn.setText("Cancel");
        uxCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uxTh160Btn)
                    .addComponent(uxTh180Btn)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uxThOtherBtn)
                        .addGap(18, 18, 18)
                        .addComponent(uxOtherThSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uxConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(uxCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uxTh160Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uxTh180Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uxThOtherBtn)
                    .addComponent(uxOtherThSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uxConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uxCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uxConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxConfirmBtnActionPerformed
        if (uxTh160Btn.isSelected()) {thresholdToReturn = 160;}
        else if (uxTh180Btn.isSelected()) {thresholdToReturn = 180;}
        else if (uxThOtherBtn.isSelected()) {thresholdToReturn = (int)uxOtherThSpnr.getValue();}
        else {JOptionPane.showMessageDialog(this, "No Threshold Selected. Something's Wrong.");}
        this.setVisible(false);
    }//GEN-LAST:event_uxConfirmBtnActionPerformed

    private void uxCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxCancelBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_uxCancelBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton uxCancelBtn;
    private javax.swing.JButton uxConfirmBtn;
    private javax.swing.JSpinner uxOtherThSpnr;
    private javax.swing.ButtonGroup uxSetThBtnGrp;
    private javax.swing.JRadioButton uxTh160Btn;
    private javax.swing.JRadioButton uxTh180Btn;
    private javax.swing.JRadioButton uxThOtherBtn;
    // End of variables declaration//GEN-END:variables
}
