/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Nicholas.Sixbury
 */
public class UnsharpDialog extends javax.swing.JDialog {

    public double unsharp_sigma = 1.5;
    public double unsharp_weight = 0.5;

    /**
     * Creates new form UnsharpDialog
     */
    public UnsharpDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Updates interface based on public vars
     */
    public void updateInterface() {
        this.uxUnsharpSigmaSpnr.setValue(unsharp_sigma);
        this.uxUnsharpWeightSpnr.setValue(unsharp_weight);
    }

    @Override
    public void setVisible(boolean visibility) {
        updateInterface();
        super.setVisible(visibility);
    }//end setVisible

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        uxParametersWhyBtn = new javax.swing.JButton();
        uxUnsharpSigmaSpnr = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uxUnsharpWeightSpnr = new javax.swing.JSpinner();
        uxParametersWhatBtn = new javax.swing.JButton();
        uxCancelBtn = new javax.swing.JButton();
        uxConfirmBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unsharp Mask Configuration");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Please configure settings for unsharp mask applied to scanned image.");

        uxParametersWhyBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uxParametersWhyBtn.setText("Why is this needed?");
        uxParametersWhyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxParametersWhyBtnActionPerformed(evt);
            }
        });

        uxUnsharpSigmaSpnr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uxUnsharpSigmaSpnr.setModel(new javax.swing.SpinnerNumberModel(1.5d, 0.5d, 3.0d, 0.1d));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Unsharp Mask Sigma");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Unsharp Mask Weight");

        uxUnsharpWeightSpnr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uxUnsharpWeightSpnr.setModel(new javax.swing.SpinnerNumberModel(0.5d, 0.1d, 0.9d, 0.1d));
        uxUnsharpWeightSpnr.setToolTipText("");

        uxParametersWhatBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uxParametersWhatBtn.setText("What do parameters mean?");
        uxParametersWhatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxParametersWhatBtnActionPerformed(evt);
            }
        });

        uxCancelBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uxCancelBtn.setText("Cancel");
        uxCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxCancelBtnActionPerformed(evt);
            }
        });

        uxConfirmBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uxConfirmBtn.setText("Confirm");
        uxConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxConfirmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(uxUnsharpSigmaSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(uxUnsharpWeightSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uxParametersWhyBtn)
                                    .addComponent(uxParametersWhatBtn))
                                .addGap(18, 18, 18)
                                .addComponent(uxCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(uxConfirmBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(uxUnsharpSigmaSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(uxUnsharpWeightSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uxParametersWhatBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uxParametersWhyBtn))
                    .addComponent(uxCancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(uxConfirmBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uxConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxConfirmBtnActionPerformed
        this.unsharp_sigma = (double)this.uxUnsharpSigmaSpnr.getValue();
        this.unsharp_weight = (double)this.uxUnsharpWeightSpnr.getValue();
        this.setVisible(false);
    }//GEN-LAST:event_uxConfirmBtnActionPerformed

    private void uxCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxCancelBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_uxCancelBtnActionPerformed

    private void uxParametersWhatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxParametersWhatBtnActionPerformed
        String message = "Taken from https://imagej.net/ij/docs/menus/process.html#filters :\n\"Unsharp masking subtracts a blurred copy \nof the image and rescales the image to obtain the same contrast \nof large (low-frequency) structures as in the input image. This \nis equivalent to adding a high-pass filtered image and thus \nsharpens the image. (Sigma) Radius is the standard deviation \n(blur radius) of the Gaussian blur that is subtracted. Mask Weight \ndetermines the strength of filtering, whereby Mask Weight=1 would \nbe an infinite weight of the high-pass filtered image that is added.\"";
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_uxParametersWhatBtnActionPerformed

    private void uxParametersWhyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxParametersWhyBtnActionPerformed
        String message = "" + 
        "This program seeks to recreate certain scan settings from the \nEPSON Scan utility. The settings we seek to recreate used EPSON's \nunsharp mask, but because that's a post-processing effect, it's \nnot accessible through TWAIN or Morena, and we therefore have to \nrecreate that effect separately. EPSON does not provide the exact \nparameters used for their unsharp mask, so instead it is \npartially left to the user to find parameters that fit their needs.";
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_uxParametersWhyBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton uxCancelBtn;
    private javax.swing.JButton uxConfirmBtn;
    private javax.swing.JButton uxParametersWhatBtn;
    private javax.swing.JButton uxParametersWhyBtn;
    private javax.swing.JSpinner uxUnsharpSigmaSpnr;
    private javax.swing.JSpinner uxUnsharpWeightSpnr;
    // End of variables declaration//GEN-END:variables
}
